spring:
  application:
    name: tech_challenge_02
data:
  mongodb:
    host: localhost
    port: 27017
    database: techchallenge
    username: admin
    password: admin
    authentication-database: admin
server:
  port: 8080